### ISSUE TITLE
Timeout error in large list file transfer

### ISSUE THREAD

**Issue by MarioClueless** [stenevang/sftp#1]
Hi guys,

I have a list of about 600 files to transfer from multiple subfolders in an sftp server. 

I can usually use sftp for this so far without issue. Today though I've been having failures to transfer with error code :

(I've obviously reducted connection info for security reasons sorry)
`Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to server_address_reducted port REDUCTED: Timed out`

My code looks like this:

`sftp_con <- sftp_connect(server = "",
                         folder = "",
                         username = "",
                         password = "",
                         protocol = "sftp://" , 
                         port = "")

sftp_makedir("./____/Data/")
sftp_changedir("./ModelData/Data/")

done <- pblapply(split(upload_fileList, upload_fileList$SN, drop = T), function(filedata){
  
  sftp_upload(file =  filedata$filename, fromfolder = filedata$ParentFolder )
  
  out <- 1
  return(out)
  
} )
print(paste("Done"))`

Using the opportunity, I feel it'd be much faster to feed the function a list of strings the string being the complete filepath of the file like C:/myfile/myfile.csv

Any ideas how I can correct my timeout error? 

Thanks in advance !

**Comment by stenevang** [comment]
I should thing your problem will be solved if you split your list of files in a few chunks and upload one chunk at a time, each time calling both sftp_connect and sftp_upload. The timeout problem is most likely that the authentication expires.
