### ISSUE TITLE
sftp_listdirs typo

### ISSUE THREAD

**Issue by samterfa** [stenevang/sftp#2]
Thanks for the useful package! There's a small typo in the sftp_listdirs function causing an error. I corrected it in my environment and fixing the typo fixed the issue. 

sft_connection should read sftp_connection below in your function.

sftp_listdirs <- function(sftp_connection = sftp_con,
                          verbose = TRUE,
                          curlPerformVerbose = FALSE,
                          recurse = FALSE) {

    final <- sftp_list(sftp_connection = sft_connection, ...

Thanks!

**Comment by stenevang** [comment]
Thank you for spotting this, Sam. Corrected now!
